# This workflow will do a clean installation of node dependencies,
# build the source code, run tests, and then build & push Docker image.

name: Node.js CI + Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job untuk testing dan validasi kode Node.js
  build:
    runs-on: ubuntu-latest
    # Set timeout untuk mencegah job berjalan terlalu lama
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout source code dari repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js dengan versi yang ditentukan
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies menggunakan npm ci
      - name: Install dependencies
        run: npm ci

      # Build project jika ada script build
      - name: Build project
        run: npm run build --if-present

      # Skip test jika tidak ada script test atau gunakan echo sebagai placeholder
      - name: Run tests
        run: npm test --if-present || echo "No tests specified, skipping..."

  # Job untuk build dan push Docker image
  docker:
    runs-on: ubuntu-latest
    # Hanya jalankan jika job build berhasil
    needs: build
    # Hanya untuk push ke main branch, tidak untuk pull request
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # Set timeout untuk Docker operations
    timeout-minutes: 15

    steps:
      # Checkout source code untuk Docker build
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Docker Buildx untuk advanced features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login ke Docker Hub menggunakan secrets yang sudah dikonfigurasi
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build dan push Docker image dalam satu step
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Build context
          push: true # Push ke registry
          tags: ${{ secrets.DOCKER_USERNAME }}/praktikum-popl-nodejs:latest # Dynamic tag menggunakan username dari secrets
          platforms: linux/amd64,linux/arm64 # Multi-platform build
          cache-from: type=gha # GitHub Actions cache
          cache-to: type=gha,mode=max # Save cache untuk build berikutnya
